### ISSUE TITLE
Adicionar Repositório no Packagist

### ISSUE THREAD

**Issue by pedro-stanaka** [jrbasso/cake_ptbr#37]
Já que a instalação via composer se tornou a forma padrão ( e recomendada) para instalar o Cake3 seria bom o repositório estar também disponível no packagist.

**Comment by jrbasso** [comment]
O projeto já estava lá pro 2.x. Também criei a tag `2.0.0` pra ficar mais facil pra quem usa.

dev-master agora contem a versão do seu PR. Vou fazer alguns testes e talvez alguns ajustes antes de gerar a tag `3.0.0`.

Muito obrigado!
