### ISSUE TITLE
Problema com o plugin

### ISSUE THREAD

**Issue by yardz** [jrbasso/cake_ptbr#39]
Cara blz?
Eu não estou conseguindo fazer seu plugin funcionar de forma alguma.

Eu segui passo a passa a instalação, mas os inflections não funcionaram nem a tradução. Sabe se tem alguma configuração que você esqueceu de colocar no "Docs" ?

**Comment by yardz** [comment]
Cara, busquei no grupo do google e encontrei outras pessoas com o mesmo problema.

Os meus problemas são:
-Inflections não funciona
-Mensagens do core não estão traduzidas
(Não sei quanto as outras mensagens. Nas minhas aplicações eu construo msg padronizada)

Eu verifiquei e seu arquivo de bootstrap.php não está sendo chamado. Outro ponto é que nele há duas linhas e nelas existem alguns problemas:

include Plugin::path('CakePtbr') . 'Config' . DS . 'traducao_core.php';
include Plugin::path('CakePtbr') . 'Config' . DS . 'inflections.php';

-A pasta "Config" agora é "config"
-O arquivo "traducao_core.php" não existe no seu plugin.


Para resolver o problema do inflections eu adicionei a seguinte linha no meu bootstrap.php (o meu, não o do plugin):
require "../plugins/CakePtbr/config/inflections.php";

Isso resolveu o problema do inflections.

**Comment by alexsmonte** [comment]
@yardz ja corrigi o problema so falta ele autorizar.

**Comment by alexsmonte** [comment]
@jrbasso  tu morreu mano ? auhhuahuhuahua

**Comment by alexsmonte** [comment]
Correção feita
